name: fitness
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Bloc
  flutter_bloc: ^8.1.1 
  # flutter_bloc: ^7.0.1

  #firebase
  firebase_core: ^2.3.0

  firebase_core_platform_interface: ^4.5.1

  material: ^1.0.0+2

  dots_indicator: ^2.0.0

  percent_indicator: ^3.0.1

  onboarding: ^3.1.0

  firebase_storage: ^11.0.6


  # flutter_local_notifications: ^9.0.0
  # flutter_local_notifications: ^12.0.4
  flutter_local_notifications: ^9.7.1

  permission_handler: ^10.2.0

  image_picker: ^0.8.2

  url_launcher: ^6.1.7


  custom_timer: ^0.1.2


  chewie: ^1.3.6

  video_player: ^2.4.8

  sliding_up_panel: ^2.0.0+1

  flutter_secure_storage: ^5.1.0

  json_serializable: ^6.5.4

  flutter_native_timezone: ^2.0.0
  
  plugin_platform_interface: ^2.1.3

  cloud_firestore: ^4.1.0

  cloud_functions: ^4.0.5

  # timezone: ^0.8.0

  rxdart: ^0.27.4



  meta: ^1.8.0
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/exercises/
    - assets/icons/home/
    - assets/icons/workouts/
    - assets/icons/social_networks/
    - assets/videos/workouts/


  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700